project:
  type: website
  output-dir: docs

website:
  title: "R Workshop"
  site-url: https://osu-codeclub.github.io/carpentries-feb-2026
  repo-url: https://github.com/osu-codeclub/carpentries-feb-2026
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: "0: Installation"
        href: 0_setup.qmd
      - text: "1: Intro"
        href: 1_intro.qmd
      - text: "2: Data Structures"
        href: 2_data-structures.qmd
      - text: "3: Data Wrangling"
        href: 3_dplyr.qmd
      - text: "4: Data Visualization"
        href: 4_ggplot.qmd
    right:
      - text: "To learn more"
        menu:
        - text: OSU Code Club {{< fa external-link >}}
          href: https://osu-codeclub.github.io
        - text: Full Carpentries workshop page {{< fa external-link >}}
          href: https://imageomics.github.io/2026-02-09-osu-online/         
        - text: Sister workshop on Version Control with Git {{< fa external-link >}}
          href: https://library.osu.edu/events/version-control-with-git
        - text: Other OSU coding activities {{< fa external-link >}}
          href: https://osu-codeclub.github.io/pages/other.html          
        - text: "------------------"
        - text: OSU Research Commons {{< fa external-link >}}
          href: https://library.osu.edu/researchcommons
        - text: The Carpentries {{< fa external-link >}}
          href: https://carpentries.org
        - text: "------------------"
        - text: The full focal Carpentries lesson {{< fa external-link >}}
          href: https://swcarpentry.github.io/r-novice-gapminder/
        - text: R for Data Science ebook {{< fa external-link >}}
          href: https://r4ds.hadley.nz
      - text: About
        href: about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/osu-codeclub/carpentries-feb-2026
          - text: Report an Issue
            url:  https://github.com/osu-codeclub/carpentries-afeb-2026/issues/new?template=Blank+issue

format:
  html:
    theme: yeti
    highlight-style: atom-one
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 800px

knitr:
  opts_chunk:
    class-output: regular-r-output
    class-message: regular-r-output
    class-warning: warning-r-output
    class-error: error-r-output
